// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMQqarL7AfzHg5JN_iEWEEQxpTk6GW0SU',
    appId: '1:259228862125:web:708a10a050f01998426824',
    messagingSenderId: '259228862125',
    projectId: 'gg-tv-42fbc',
    authDomain: 'gg-tv-42fbc.firebaseapp.com',
    storageBucket: 'gg-tv-42fbc.appspot.com',
    measurementId: 'G-429FX6850H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQx5Q964L7Ze38aCtpMyYMmDIdR4Qjg_8',
    appId: '1:259228862125:android:bfdf134c38ff6b73426824',
    messagingSenderId: '259228862125',
    projectId: 'gg-tv-42fbc',
    storageBucket: 'gg-tv-42fbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5f4P-1MH14FRL2bQlpx3kvo-i_khCDs',
    appId: '1:259228862125:ios:09df7db945b54c21426824',
    messagingSenderId: '259228862125',
    projectId: 'gg-tv-42fbc',
    storageBucket: 'gg-tv-42fbc.appspot.com',
    iosClientId:
        '259228862125-58kpbc0i291h4erj3o6v1vqfots2k0q6.apps.googleusercontent.com',
    iosBundleId: 'com.normal.ggtv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj5f4P-1MH14FRL2bQlpx3kvo-i_khCDs',
    appId: '1:259228862125:ios:09df7db945b54c21426824',
    messagingSenderId: '259228862125',
    projectId: 'gg-tv-42fbc',
    storageBucket: 'gg-tv-42fbc.appspot.com',
    iosClientId:
        '259228862125-58kpbc0i291h4erj3o6v1vqfots2k0q6.apps.googleusercontent.com',
    iosBundleId: 'com.normal.ggtv',
  );
}
